version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "daily"
      time: "00:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
